name: DingTalk Notify On Issue
on:
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created, edited]
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Install
        run: |
          yarn
      - name: Build
        run: |
          yarn build
      - name: Prepare
        id: prepare
        run: |
          event_name=${{ github.event_name }}
          if [ $event_name == "issues" ]
          then
            card_title="[${{ github.event.issue.user.login }}](${{ github.event.issue.user.html_url }}) **${{ github.event.action }}** issue: ${{ github.event.issue.title }} ([#${{ github.event.issue.number }}](${{ github.event.issue.html_url }}))"
            card_avatar="![avatar](${{ github.event.issue.user.avatar_url }})"
            card_link="${{ github.event.issue.html_url }}"
            card_body=${{ toJSON(github.event.issue.body) }}
          else
            card_title="[${{ github.event.comment.user.login }}](${{ github.event.comment.user.html_url }}) **${{ github.event.action }}** comment of issue: ${{ github.event.issue.title }} ([#${{ github.event.issue.number }}](${{ github.event.issue.html_url }}))"
            card_avatar="![avatar](${{ github.event.comment.user.avatar_url }})"
            card_link="${{ github.event.comment.html_url }}"
            card_body=${{ toJSON(github.event.comment.body) }}
          fi

          echo "::set-output name=card_title::$card_title"
          echo "::set-output name=card_avatar::$card_avatar"
          echo "::set-output name=card_link::$card_link"
          echo "::set-output name=card_body::$card_body"
      - name: Send
        uses: ./
        with:
          token: ${{ secrets.DINGTALK_TOKEN }}
          secret: ${{ secrets.DINGTALK_SECRET }}
          msgtype: actionCard
          content: |
            {
              "title": "${{ steps.prepare.outputs.card_title }}",
              "text": "${{ steps.prepare.outputs.card_avatar }} \n\n${{ steps.prepare.outputs.card_title }} \n\n ${{ steps.prepare.outputs.card_body }}",
              "singleURL": "${{ steps.prepare.outputs.card_link }}",
              "singleTitle": "查看详情"
            }
